#Generated file - don't edit (please)
#Sat May 03 20:29:35 GMT+07:00 2025
ftpserver.user.son.enableflag=true
ftpserver.user.son.homedirectory=ftp-root/son
ftpserver.user.son.idletime=0
ftpserver.user.son.userpassword=E10ADC3949BA59ABBE56E057F20F883E
ftpserver.user.son.writepermission=true
